### ISSUE TITLE
Export on filtered list

### ISSUE THREAD

**Issue by vanhoutenbos** [bskinn/excel-csvexporter#21]
Is possible to extend this functionality so that I can export a filtered list?

**Comment by bskinn** [comment]
Probably the easiest way to make this happen would be to update the plugin with a toggle to include/exclude hidden rows from the export.

Then, you could use Excel's built-in tooling to do the filtering:

![image](https://user-images.githubusercontent.com/11325439/65251682-c2048780-dac5-11e9-9384-4dabcb9da754.png)

And export only the non-hidden rows.

How's that sound?

**Comment by vanhoutenbos** [comment]
This sounds like a good solution! I am currently looking at a quick
workaround by writing a VB.NET macro

Op do 19 sep. 2019 om 16:10 schreef Brian Skinn <notifications@github.com>:
