### ISSUE TITLE
Add top row

### ISSUE THREAD

**Issue by vanhoutenbos** [bskinn/excel-csvexporter#22]
Is it possible to add an option to (take) the first row, and add it to the .csv list?
I have a row with headers that i need in every csv.

**Comment by bskinn** [comment]
Should be. 

Take the following situation:

![image](https://user-images.githubusercontent.com/11325439/65251357-2ecb5200-dac5-11e9-9392-81f973735808.png)


Is it that you'd like to be able to have an option to include row 2 in the CSV? E.g., a checkbox with options like:

```
[X] Include header rows [    2] through [    2]
```

?

**Comment by bskinn** [comment]
@jeanpoelie, I have a [dev release](https://github.com/bskinn/excel-csvexporter/releases/tag/v1.2.0.dev1) up with this header-row feature and that from #21 (giving the option to skip hidden rows/columns).

Could you download this 1.2.0.dev1 and give it a try, see if it works the way you want/expect?

Thanks!

**Comment by vanhoutenbos** [comment]
I will try this out soon! Probably tomorrow

**Comment by bskinn** [comment]
New [dev release](https://github.com/bskinn/excel-csvexporter/releases/tag/v1.2.0.dev2), with bugfix.

**Comment by vanhoutenbos** [comment]
Very late response, This seems to have worked for me! I tested it 2 months ago but forgot to report back due to distractions!

**Comment by bskinn** [comment]
@jeanpoelie Terrific! 👍 

Thanks for the feature request!

**Comment by vanhoutenbos** [comment]
Not a problem! Have a great day and im sure ill be back in the future :D
