### ISSUE TITLE
quote delimited

### ISSUE THREAD

**Issue by mckennatim** [bskinn/excel-csvexporter#24]
tried using the addin to import csv parameters into fusion 360. It wants to see quote delimited

**Comment by bskinn** [comment]
As in, each item needs to be surrounded in quotes, in addition to the (e.g.) comma delimiter?

**Comment by bskinn** [comment]
Sample csv's in [this thread](https://forums.autodesk.com/t5/fusion-360-design-validate/importing-csv/td-p/5444014).

**Comment by mckennatim** [comment]
Yep, and excel exports without as csv without double quotes. I ended up writing a little utility.

`
var fs = require('fs');
var output;
var lineReader = require('readline').createInterface({
    input: fs.createReadStream(__dirname + '/exout.csv')
});

var output = fs.createWriteStream(__dirname + '/outx.csv');

lineReader.on('line', function (line) {
    var array = line.split(',');
    let modline = array.map((a)=>{
      return  `"${a}"`
    })
    modline += "\r\n";
    output.write(modline)
});

`

**Comment by bskinn** [comment]
&lt;nod&gt;, it should be straightforward to add an option for that.  I'm hoping to have a new release out within a few weeks that adds this feature, as well as the header capability of #22.

**Comment by bskinn** [comment]
Finally got this implemented, @mckennatim. Give the [v1.2.0](https://github.com/bskinn/excel-csvexporter/releases/tag/v1.2.0) version a try, see if it does what you want.
