### ISSUE TITLE
Export cell with text

### ISSUE THREAD

**Issue by Nico128** [bskinn/excel-csvexporter#28]
Hi

Ice add-on. I have cells which contain text. But the text isn't quoted in the export.
That's a problem for some CSV readers.

Thank you

**Comment by bskinn** [comment]
Glad you like it!

Is what you're looking for similar to what's described in #24? I've had that on my to-do list for a while now; I need to actually get it implemented!

**Comment by Nico128** [comment]
Yes it's similar, if I correctly understood what this user needs.

Many tools require quoted texts.

Example
![image](https://user-images.githubusercontent.com/7404813/83196885-ea588180-a13c-11ea-8d47-c91581535647.png)

**Comment by bskinn** [comment]
Got this implemented, @Nico128. Give the [v1.2.0](https://github.com/bskinn/excel-csvexporter/releases/tag/v1.2.0) version a try, see if it does what you want.
