### ISSUE TITLE
Ctrl+Shift+C Issue

### ISSUE THREAD

**Issue by bnj20704** [bskinn/excel-csvexporter#32]
I have been using this program for a year now and have had the same problem. If I have the add-in enabled straight from opening the document, the commands do not work. I have to go in and disable the add-in and then re-enable it in order for it to work. I haven't minded doing this because I'm hourly but it would be nice to troubleshoot why it isn't working 100& of the time. I understand that this program hasn't been updated since 2020 but any help is greatly appreciated. This happens with Win 10. I have also used the program with Microsoft 365 and 2019 and the same issue is present.

**Comment by bskinn** [comment]
I'll take a look at it and see what I can figure out. I haven't been seeing this problem with my other addins, but I actually don't regularly use this one much myself, so I can't say for sure it's working ok on my computer. 

If nothing else, I can add alternative instructions for how to set the macro up on a custom Ribbon button, which *should* be more robust.

**Comment by bnj20704** [comment]
I appreciate you looking into this and look forward to the custom ribbon button instructions! Thank you!

**Comment by bskinn** [comment]
New instructions for a Ribbon button are [here](https://github.com/bskinn/excel-csvexporter/wiki/Installation-&-Execution#optional-launch-button-in-ribbon)!
