### ISSUE TITLE
Formatting dates

### ISSUE THREAD

**Issue by Mastomaki** [bskinn/excel-csvexporter#34]
Formatting of dates needs improvement. For example

Excel
-----
1.1.2018 0:00
1.1.2018 1:00

CSV
----
1.1.2018
1.1.2018 1.00.00

**Comment by bskinn** [comment]
Are you just using the default `@` formatting code?

**Comment by Mastomaki** [comment]
Yes. How would you suggest to change it?

**Comment by bskinn** [comment]
One example of a date/time format is: `mm/dd/yyyy hh:mmAM/PM`.

If you don't want leading zeros on the month, day or hour, use `m` or `d` or `h` instead of `mm`/`dd`/`hh`.

If you only want a two-digit year, use `yy`.

If you'd prefer a 24-hour time instead of an AM/PM time, remove the `AM/PM`.
