### ISSUE TITLE
Crop the end of long texts

### ISSUE THREAD

**Issue by balintrichly** [bskinn/excel-csvexporter#36]
I exported a selection with long text values in the fields, but after 256 characters the end of the text has been truncated for each field.

**Comment by bskinn** [comment]
Hmm, interesting.  To be sure I understand: is it truncating *each cell* to 256 characters? Or is it truncating *each row* to 256?

Could you attach a sample Excel sheet here that shows the behavior, so that I have something to test with?

**Comment by balintrichly** [comment]
Each cell to 256 characters. Here is an example sheet with the first 200 numbers comma separated. I exported only the A1 cell with pipe separation and it happend again, after 88, no more character exported. I also attached the output csv file.

[first200number.csv](https://github.com/bskinn/excel-csvexporter/files/8193455/first200number.csv)
[first200number.xlsx](https://github.com/bskinn/excel-csvexporter/files/8193456/first200number.xlsx)

**Comment by bskinn** [comment]
Interesting. I'm using VBA's `Format` function to apply the number format specified on the GUI, and it apparently truncates its output to 255 characters.  I believe I have a fix in place; I'll test it for a bit and then release a new version, and we'll see if it fixes this problem. Stay tuned....

**Comment by bskinn** [comment]
Ok, give v1.2.2 a shot, see if it works correctly for you: https://github.com/bskinn/excel-csvexporter/releases/tag/v1.2.2

**Comment by balintrichly** [comment]
It seems to work now, thanks for your fast feedback and for the correction.
